### ISSUE TITLE
Epi Crashes on missing nested value object parameter

### ISSUE THREAD

**Issue by jimclouse** [glg/epiquery2#145]
We discovered that some users have added sql parameters referencing nested values such as `--@color varchar pants.color`

If `pants` doesn't exist, the epi worker dies. 

Let's fix this so it handles it gracefully.

**Comment by jimclouse** [comment]
Also, should we even support this? Kind of sounds useful, but also, kind of unnecessary.

**Comment by wballard** [comment]
👖On Mar 3, 2023, at 4:17 PM, Jim Clouse ***@***.***> wrote:﻿
We discovered that some users have added sql parameters referencing nested values such as ***@***.*** varchar pants.color
If pants doesn't exist, the epi worker dies.
Let's fix this so it handles it gracefully.
