### ISSUE TITLE
Unable to run Snowflake tests locally

### ISSUE THREAD

**Issue by fearphage** [glg/epiquery2#68]
Related to #63 

The local config for snowflake is not configured correctly. The (3) snowflake tests just run until they timeout and drastically slow down the test run. 

Do we need to bug snowflake for a dev account?
Do we need to skip these for local dev (somehow)?

This needs to be addressed in some way.

**Comment by mikemartin1090** [comment]
I have a user account already that only has access to run these tests in the one warehouse. I can store them in AWS secrets manager OR LastPass. I think LastPass may be the better solution and just have us use the `lpass` [CLI.](https://github.com/lastpass/lastpass-cli#lastpass-cli)
